site_name: Sample Information Documentation
pages:
    - Sample Information Introduction: index.md
theme:
    name: material
    #name: readthedocs

    #palette:
    #    primary: 'light blue'
    #    accent: 'orange'
    #font:
    #    text: 'Roboto'
    #    code: 'Roboto Mono'

    #logo: 'img/GNPS_logo.jpg'
#theme: readthedocs
#theme:
#  name: 'rtd-dropdown'
google_analytics: ['UA-8412213-5', 'ccms-ucsd.github.io']
