site_name: Sample Information Documentation
pages:
    - Sample Information Introduction: index.md
    - How to Contribute: HowtoContribute.md
    - Analyze Your Data:
        - Multivariate: AnalyzeYourData_MultivariateComparisons.md
        - Co-Analysis at GNPS: AnalyzeYourData_CoAnalysis_at_GNPS.md
    - Analyze Public Data:
        - Multivariate: AnalyzePublicData_MultivariateComparisons.md
        - Chemical Enrichment: AnalyzePublicData_ChemicalEnrichment.md
        - Re-analysis at GNPS: PublicData_Reanalysis_at_GNPS.md
theme:
    name: material
    #name: readthedocs

    #palette:
    #    primary: 'light blue'
    #    accent: 'orange'
    #font:
    #    text: 'Roboto'
    #    code: 'Roboto Mono'

    #logo: 'img/GNPS_logo.jpg'
#theme: readthedocs
#theme:
#  name: 'rtd-dropdown'
google_analytics: ['UA-8412213-5', 'ccms-ucsd.github.io']
